import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type ContentLanguage = "en" | "zh";
export type Locale = ContentLanguage | "ja" | "ko" | "es";

type TranslationKey = keyof typeof translations.en;

export type LanguageOption = {
  code: Locale;
  label: string;
  shortLabel: string;
  nativeLabel: string;
  contentLanguage: ContentLanguage;
};

interface LanguageContextType {
  language: ContentLanguage;
  locale: Locale;
  languages: LanguageOption[];
  setLanguage: (lang: Locale) => void;
  t: (key: string) => string;
}

const languageOptions: LanguageOption[] = [
  { code: "en", label: "English", shortLabel: "EN", nativeLabel: "English", contentLanguage: "en" },
  { code: "zh", label: "Chinese", shortLabel: "中文", nativeLabel: "简体中文", contentLanguage: "zh" },
  { code: "ja", label: "Japanese", shortLabel: "日本語", nativeLabel: "日本語", contentLanguage: "en" },
  { code: "ko", label: "Korean", shortLabel: "한국어", nativeLabel: "한국어", contentLanguage: "en" },
  { code: "es", label: "Spanish", shortLabel: "ES", nativeLabel: "Español", contentLanguage: "en" },
];

const LOCALE_STORAGE_KEY = "ynx-locale-v3";

const translations = {
  en: {
    "language.label": "Language",
    "language.note": "Interface language",
    "language.content_note": "Long-form docs stay EN/ZH for accuracy.",
    "nav.home": "Home",
    "nav.start": "Start",
    "nav.use": "Use",
    "nav.build": "Build",
    "nav.project": "Project",
    "nav.builders": "Builders",
    "nav.validators": "Validators",
    "nav.trade": "Trade",
    "nav.bridge": "Bridge",
    "nav.withdraw": "Withdraw",
    "nav.ai": "AI",
    "nav.assets": "Assets",
    "nav.readiness": "Readiness",
    "nav.testnet": "Testnet",
    "nav.docs": "Docs",
    "nav.faq": "FAQ",
    "nav.about": "About",
    "nav.support": "Support",
    "nav.risk": "Risk",
    "nav.security": "Security",
    "nav.github": "GitHub",
    "nav.get_assets": "Get Assets",
    "nav.ai_demo": "AI Demo",
    "nav.main_path": "Main path",
    "nav.desc.start": "Get gas and test assets first.",
    "nav.desc.bridge": "Move test assets into YNX.",
    "nav.desc.withdraw": "Release wrapped assets back out.",
    "nav.desc.readiness": "Check live proof and blockers.",
    "nav.desc.docs": "Open the task-based docs hub.",
    "nav.desc.trade": "Swap test assets on the public pilot.",
    "nav.desc.ai": "Use the AI control and settlement surface.",
    "nav.desc.testnet": "Inspect endpoints and network state.",
    "nav.desc.builders": "Connect apps, RPC, wallets, and tooling.",
    "nav.desc.validators": "Run validator and infrastructure flows.",
    "nav.desc.ai_demo": "Walk through the official AI/Web4 demo.",
    "nav.desc.about": "See project scope and current boundaries.",
    "nav.desc.support": "Grant, sponsor, and early diligence entry.",
    "nav.desc.faq": "Fast answers to the main product questions.",
    "nav.desc.risk": "Current project, asset, and legal boundary risks.",
    "nav.desc.security": "Reporting process and open security gaps.",
    "hero.badge": "AI-native public testnet",
    "hero.title": "A cleaner execution layer for AI, apps, and machine payments.",
    "hero.subtitle": "YNX is an EVM-compatible execution network where humans, apps, and AI agents coordinate through policy-bounded sessions, machine-payment vaults, and verifiable settlement.",
    "hero.cta.explorer": "View Explorer",
    "hero.cta.build": "Run AI Demo",
    "hero.cta.join": "Join Testnet",
    "hero.rule": "Protocol rule",
    "hero.guide.1": "Define machine boundaries before execution starts",
    "hero.guide.2": "Issue revocable sessions instead of permanent trust",
    "hero.guide.3": "Settle AI and machine actions with verifiable proof",
    "hero.card.core.label": "Core framing",
    "hero.card.core.value": "Web4 execution layer",
    "hero.card.audience.label": "Primary audience",
    "hero.card.audience.value": "Builders, operators, AI apps",
    "hero.card.state.label": "Current state",
    "hero.card.state.value": "Public testnet on live endpoints",
    "hero.card.form.label": "Operating form",
    "hero.card.form.value": "Project stage, no public legal entity yet",
    "footer.badge": "Public Testnet Project",
    "footer.body": "YNX is currently a Web4 and AI-execution public testnet project. This site should not imply that a separate legal operating company, custodial product, or regulated financial service is already live.",
    "footer.path": "Best first path: get test assets, bridge into YNX, try a public action, withdraw back out, then inspect readiness evidence.",
    "footer.readiness": "Live readiness",
    "footer.start_here": "Start Here",
    "footer.build": "Build",
    "footer.project": "Project",
    "footer.boundary": "Public testnet only. Test assets have no mainnet value. Company formation, dedicated legal ownership, and broader institutional controls remain in progress.",
    "footer.explorer": "Explorer",
    "footer.faucet": "Faucet",
  },
  zh: {
    "language.label": "语言",
    "language.note": "界面语言",
    "language.content_note": "长文档为保证准确性保留中英版本。",
    "nav.home": "首页",
    "nav.start": "开始",
    "nav.use": "使用",
    "nav.build": "构建",
    "nav.project": "项目",
    "nav.builders": "开发者",
    "nav.validators": "验证者",
    "nav.trade": "交易",
    "nav.bridge": "跨链",
    "nav.withdraw": "提现",
    "nav.ai": "AI",
    "nav.assets": "资产",
    "nav.readiness": "证据板",
    "nav.testnet": "测试网",
    "nav.docs": "文档",
    "nav.faq": "常见问题",
    "nav.about": "关于",
    "nav.support": "支持",
    "nav.risk": "风险",
    "nav.security": "安全",
    "nav.github": "GitHub",
    "nav.get_assets": "领取资产",
    "nav.ai_demo": "AI 演示",
    "nav.main_path": "主路径",
    "nav.desc.start": "先领取 gas 和测试资产。",
    "nav.desc.bridge": "把测试资产跨入 YNX。",
    "nav.desc.withdraw": "把 wrapped 资产释放回源测试网。",
    "nav.desc.readiness": "查看实时证据与阻塞项。",
    "nav.desc.docs": "打开按任务整理的文档中心。",
    "nav.desc.trade": "在公开测试面板兑换测试资产。",
    "nav.desc.ai": "使用 AI 控制与结算界面。",
    "nav.desc.testnet": "查看端点和网络状态。",
    "nav.desc.builders": "连接应用、RPC、钱包与工具。",
    "nav.desc.validators": "运行验证者和基础设施流程。",
    "nav.desc.ai_demo": "查看官方 AI/Web4 演示。",
    "nav.desc.about": "了解项目范围与当前边界。",
    "nav.desc.support": "资助、赞助与早期尽调入口。",
    "nav.desc.faq": "快速回答主要产品问题。",
    "nav.desc.risk": "当前项目、资产和法律边界风险。",
    "nav.desc.security": "漏洞报告流程和仍待补齐的安全项。",
    "hero.badge": "AI 原生公开测试网",
    "hero.title": "为 AI、应用与机器支付打造更清晰的执行层。",
    "hero.subtitle": "YNX 是兼容 EVM 的执行网络。人类、应用与 AI 智能体在此通过策略受限会话、机器支付金库及可验证结算进行协作。",
    "hero.cta.explorer": "区块浏览器",
    "hero.cta.build": "运行 AI 演示",
    "hero.cta.join": "加入测试网",
    "hero.rule": "协议原则",
    "hero.guide.1": "在执行前定义机器可行动的边界",
    "hero.guide.2": "发放可撤销的会话权限，而不是永久信任",
    "hero.guide.3": "用可验证证明完成 AI 与机器动作结算",
    "hero.card.core.label": "核心定位",
    "hero.card.core.value": "Web4 执行层",
    "hero.card.audience.label": "主要用户",
    "hero.card.audience.value": "开发者、运营者、AI 应用",
    "hero.card.state.label": "当前状态",
    "hero.card.state.value": "公开测试网与线上端点运行中",
    "hero.card.form.label": "当前形态",
    "hero.card.form.value": "项目阶段，尚未公开设立法律实体",
    "footer.badge": "公开测试网项目",
    "footer.body": "YNX 当前是 Web4 与 AI 执行公开测试网项目。本网站不应暗示独立法律运营公司、托管产品或受监管金融服务已经上线。",
    "footer.path": "推荐路径：领取测试资产，跨入 YNX，尝试公开功能，提回源测试网，再查看 readiness 证据。",
    "footer.readiness": "实时证据板",
    "footer.start_here": "从这里开始",
    "footer.build": "构建",
    "footer.project": "项目",
    "footer.boundary": "仅限公开测试网。测试资产没有主网价值。公司设立、专门法律归属和更广泛的机构级控制仍在推进中。",
    "footer.explorer": "浏览器",
    "footer.faucet": "水龙头",
  },
  ja: {
    "language.label": "言語",
    "language.note": "UI 言語",
    "language.content_note": "長文ドキュメントは正確性のため EN/ZH のままです。",
    "nav.home": "ホーム",
    "nav.start": "開始",
    "nav.use": "使う",
    "nav.build": "構築",
    "nav.project": "プロジェクト",
    "nav.builders": "開発者",
    "nav.validators": "バリデータ",
    "nav.trade": "取引",
    "nav.bridge": "ブリッジ",
    "nav.withdraw": "出金",
    "nav.ai": "AI",
    "nav.assets": "資産",
    "nav.readiness": "証拠ボード",
    "nav.testnet": "テストネット",
    "nav.docs": "ドキュメント",
    "nav.faq": "FAQ",
    "nav.about": "概要",
    "nav.support": "支援",
    "nav.risk": "リスク",
    "nav.security": "セキュリティ",
    "nav.github": "GitHub",
    "nav.get_assets": "資産を取得",
    "nav.ai_demo": "AI デモ",
    "nav.main_path": "主要ルート",
    "nav.desc.start": "まず gas とテスト資産を取得します。",
    "nav.desc.bridge": "テスト資産を YNX に移動します。",
    "nav.desc.withdraw": "wrapped 資産を元のテストネットへ戻します。",
    "nav.desc.readiness": "ライブ証拠とブロッカーを確認します。",
    "nav.desc.docs": "タスク別のドキュメントハブを開きます。",
    "nav.desc.trade": "公開パイロットでテスト資産をスワップします。",
    "nav.desc.ai": "AI 制御と決済サーフェスを使います。",
    "nav.desc.testnet": "エンドポイントとネットワーク状態を確認します。",
    "nav.desc.builders": "アプリ、RPC、ウォレット、ツールを接続します。",
    "nav.desc.validators": "バリデータとインフラ手順を実行します。",
    "nav.desc.ai_demo": "公式 AI/Web4 デモを確認します。",
    "nav.desc.about": "プロジェクト範囲と現在の境界を確認します。",
    "nav.desc.support": "助成、スポンサー、初期デューデリジェンスの入口です。",
    "nav.desc.faq": "主要な製品質問への短い回答です。",
    "nav.desc.risk": "現在のプロジェクト、資産、法的境界リスクです。",
    "nav.desc.security": "報告プロセスと未解決の安全項目です。",
    "hero.badge": "AI ネイティブ公開テストネット",
    "hero.title": "AI、アプリ、マシン決済のためのより明快な実行レイヤー。",
    "hero.subtitle": "YNX は EVM 互換の実行ネットワークです。人、アプリ、AI エージェントが、ポリシー制限付きセッション、マシン決済ボールト、検証可能な決済で協調します。",
    "hero.cta.explorer": "Explorer を見る",
    "hero.cta.build": "AI デモを実行",
    "hero.cta.join": "テストネットに参加",
    "hero.rule": "プロトコル原則",
    "hero.guide.1": "実行前にマシンの行動境界を定義",
    "hero.guide.2": "恒久的な信頼ではなく、取消可能なセッションを発行",
    "hero.guide.3": "AI とマシンの動作を検証可能な証拠で決済",
    "hero.card.core.label": "中核定位",
    "hero.card.core.value": "Web4 実行レイヤー",
    "hero.card.audience.label": "主な対象",
    "hero.card.audience.value": "開発者、運用者、AI アプリ",
    "hero.card.state.label": "現在の状態",
    "hero.card.state.value": "ライブ端点上の公開テストネット",
    "hero.card.form.label": "運営形態",
    "hero.card.form.value": "プロジェクト段階、公開法人は未設立",
    "footer.badge": "公開テストネットプロジェクト",
    "footer.body": "YNX は現在 Web4 と AI 実行の公開テストネットプロジェクトです。このサイトは、独立した法人、カストディ製品、または規制対象金融サービスがすでに稼働していることを示すものではありません。",
    "footer.path": "最初の推奨ルート：テスト資産を取得し、YNX にブリッジし、公開アクションを試し、引き出してから readiness 証拠を確認します。",
    "footer.readiness": "ライブ証拠",
    "footer.start_here": "最初に",
    "footer.build": "構築",
    "footer.project": "プロジェクト",
    "footer.boundary": "公開テストネットのみ。テスト資産にメインネット価値はありません。会社設立、専用の法的所有、より広い機関向け管理は進行中です。",
    "footer.explorer": "Explorer",
    "footer.faucet": "Faucet",
  },
  ko: {
    "language.label": "언어",
    "language.note": "인터페이스 언어",
    "language.content_note": "긴 문서는 정확성을 위해 EN/ZH로 유지됩니다.",
    "nav.home": "홈",
    "nav.start": "시작",
    "nav.use": "사용",
    "nav.build": "빌드",
    "nav.project": "프로젝트",
    "nav.builders": "빌더",
    "nav.validators": "검증자",
    "nav.trade": "거래",
    "nav.bridge": "브리지",
    "nav.withdraw": "출금",
    "nav.ai": "AI",
    "nav.assets": "자산",
    "nav.readiness": "증거 보드",
    "nav.testnet": "테스트넷",
    "nav.docs": "문서",
    "nav.faq": "FAQ",
    "nav.about": "소개",
    "nav.support": "지원",
    "nav.risk": "리스크",
    "nav.security": "보안",
    "nav.github": "GitHub",
    "nav.get_assets": "자산 받기",
    "nav.ai_demo": "AI 데모",
    "nav.main_path": "주요 경로",
    "nav.desc.start": "먼저 gas와 테스트 자산을 받습니다.",
    "nav.desc.bridge": "테스트 자산을 YNX로 이동합니다.",
    "nav.desc.withdraw": "wrapped 자산을 원본 테스트넷으로 되돌립니다.",
    "nav.desc.readiness": "실시간 증거와 블로커를 확인합니다.",
    "nav.desc.docs": "작업별 문서 허브를 엽니다.",
    "nav.desc.trade": "공개 파일럿에서 테스트 자산을 스왑합니다.",
    "nav.desc.ai": "AI 제어 및 정산 화면을 사용합니다.",
    "nav.desc.testnet": "엔드포인트와 네트워크 상태를 확인합니다.",
    "nav.desc.builders": "앱, RPC, 지갑, 도구를 연결합니다.",
    "nav.desc.validators": "검증자와 인프라 절차를 실행합니다.",
    "nav.desc.ai_demo": "공식 AI/Web4 데모를 확인합니다.",
    "nav.desc.about": "프로젝트 범위와 현재 경계를 확인합니다.",
    "nav.desc.support": "그랜트, 스폰서, 초기 실사 입구입니다.",
    "nav.desc.faq": "핵심 제품 질문에 대한 빠른 답변입니다.",
    "nav.desc.risk": "현재 프로젝트, 자산, 법적 경계 리스크입니다.",
    "nav.desc.security": "보고 절차와 남은 보안 과제입니다.",
    "hero.badge": "AI 네이티브 공개 테스트넷",
    "hero.title": "AI, 앱, 머신 결제를 위한 더 선명한 실행 레이어.",
    "hero.subtitle": "YNX는 EVM 호환 실행 네트워크입니다. 사람, 앱, AI 에이전트가 정책 제한 세션, 머신 결제 볼트, 검증 가능한 정산으로 협업합니다.",
    "hero.cta.explorer": "Explorer 보기",
    "hero.cta.build": "AI 데모 실행",
    "hero.cta.join": "테스트넷 참여",
    "hero.rule": "프로토콜 원칙",
    "hero.guide.1": "실행 전에 머신의 행동 경계를 정의",
    "hero.guide.2": "영구 신뢰 대신 취소 가능한 세션 발급",
    "hero.guide.3": "검증 가능한 증거로 AI와 머신 동작 정산",
    "hero.card.core.label": "핵심 프레이밍",
    "hero.card.core.value": "Web4 실행 레이어",
    "hero.card.audience.label": "주요 대상",
    "hero.card.audience.value": "빌더, 운영자, AI 앱",
    "hero.card.state.label": "현재 상태",
    "hero.card.state.value": "라이브 엔드포인트의 공개 테스트넷",
    "hero.card.form.label": "운영 형태",
    "hero.card.form.value": "프로젝트 단계, 공개 법인은 아직 없음",
    "footer.badge": "공개 테스트넷 프로젝트",
    "footer.body": "YNX는 현재 Web4 및 AI 실행 공개 테스트넷 프로젝트입니다. 이 사이트는 별도 법인, 커스터디 제품 또는 규제 금융 서비스가 이미 운영 중임을 의미하지 않습니다.",
    "footer.path": "권장 첫 경로: 테스트 자산을 받고, YNX로 브리지하고, 공개 기능을 시도하고, 다시 출금한 뒤 readiness 증거를 확인합니다.",
    "footer.readiness": "실시간 증거",
    "footer.start_here": "시작하기",
    "footer.build": "빌드",
    "footer.project": "프로젝트",
    "footer.boundary": "공개 테스트넷 전용입니다. 테스트 자산은 메인넷 가치가 없습니다. 회사 설립, 전담 법적 소유권, 더 넓은 기관 수준 통제는 아직 진행 중입니다.",
    "footer.explorer": "Explorer",
    "footer.faucet": "Faucet",
  },
  es: {
    "language.label": "Idioma",
    "language.note": "Idioma de interfaz",
    "language.content_note": "Los documentos largos se mantienen en EN/ZH por precisión.",
    "nav.home": "Inicio",
    "nav.start": "Empezar",
    "nav.use": "Usar",
    "nav.build": "Construir",
    "nav.project": "Proyecto",
    "nav.builders": "Builders",
    "nav.validators": "Validadores",
    "nav.trade": "Trade",
    "nav.bridge": "Bridge",
    "nav.withdraw": "Retirar",
    "nav.ai": "AI",
    "nav.assets": "Activos",
    "nav.readiness": "Pruebas",
    "nav.testnet": "Testnet",
    "nav.docs": "Docs",
    "nav.faq": "FAQ",
    "nav.about": "Acerca de",
    "nav.support": "Apoyo",
    "nav.risk": "Riesgo",
    "nav.security": "Seguridad",
    "nav.github": "GitHub",
    "nav.get_assets": "Obtener activos",
    "nav.ai_demo": "Demo AI",
    "nav.main_path": "Ruta principal",
    "nav.desc.start": "Obtén gas y activos de prueba primero.",
    "nav.desc.bridge": "Mueve activos de prueba hacia YNX.",
    "nav.desc.withdraw": "Libera activos wrapped de vuelta al testnet origen.",
    "nav.desc.readiness": "Revisa pruebas en vivo y bloqueos.",
    "nav.desc.docs": "Abre el hub de documentos por tarea.",
    "nav.desc.trade": "Intercambia activos de prueba en el piloto público.",
    "nav.desc.ai": "Usa la superficie de control y liquidación AI.",
    "nav.desc.testnet": "Inspecciona endpoints y estado de red.",
    "nav.desc.builders": "Conecta apps, RPC, wallets y tooling.",
    "nav.desc.validators": "Ejecuta flujos de validadores e infraestructura.",
    "nav.desc.ai_demo": "Recorre la demo oficial AI/Web4.",
    "nav.desc.about": "Consulta alcance y límites actuales.",
    "nav.desc.support": "Entrada para grants, sponsors y diligence temprana.",
    "nav.desc.faq": "Respuestas rápidas a preguntas principales.",
    "nav.desc.risk": "Riesgos actuales de proyecto, activos y límites legales.",
    "nav.desc.security": "Proceso de reporte y brechas abiertas de seguridad.",
    "hero.badge": "Testnet pública nativa de AI",
    "hero.title": "Una capa de ejecución más clara para AI, apps y pagos de máquina.",
    "hero.subtitle": "YNX es una red de ejecución compatible con EVM donde personas, apps y agentes de AI coordinan mediante sesiones con límites de política, bóvedas de pago de máquina y liquidación verificable.",
    "hero.cta.explorer": "Ver Explorer",
    "hero.cta.build": "Ejecutar demo AI",
    "hero.cta.join": "Unirse al testnet",
    "hero.rule": "Regla de protocolo",
    "hero.guide.1": "Definir límites de máquina antes de ejecutar",
    "hero.guide.2": "Emitir sesiones revocables en vez de confianza permanente",
    "hero.guide.3": "Liquidar acciones de AI y máquina con prueba verificable",
    "hero.card.core.label": "Marco central",
    "hero.card.core.value": "Capa de ejecución Web4",
    "hero.card.audience.label": "Audiencia principal",
    "hero.card.audience.value": "Builders, operadores, apps AI",
    "hero.card.state.label": "Estado actual",
    "hero.card.state.value": "Testnet pública con endpoints vivos",
    "hero.card.form.label": "Forma operativa",
    "hero.card.form.value": "Etapa de proyecto, sin entidad legal pública aún",
    "footer.badge": "Proyecto de testnet pública",
    "footer.body": "YNX es actualmente un proyecto de testnet pública para Web4 y ejecución de AI. Este sitio no debe implicar que una compañía operativa separada, producto de custodia o servicio financiero regulado ya esté activo.",
    "footer.path": "Mejor ruta inicial: obtener activos de prueba, hacer bridge hacia YNX, probar una acción pública, retirar de vuelta y revisar evidencia de readiness.",
    "footer.readiness": "Pruebas en vivo",
    "footer.start_here": "Empieza aquí",
    "footer.build": "Construir",
    "footer.project": "Proyecto",
    "footer.boundary": "Solo testnet pública. Los activos de prueba no tienen valor en mainnet. La formación de compañía, propiedad legal dedicada y controles institucionales más amplios siguen en progreso.",
    "footer.explorer": "Explorer",
    "footer.faucet": "Faucet",
  },
} satisfies Record<Locale, Partial<Record<string, string>>> & { en: Record<string, string> };

function normalizeLocale(value: string | null): Locale {
  if (value && languageOptions.some((item) => item.code === value)) return value as Locale;
  if (value?.toLowerCase().startsWith("zh")) return "zh";
  if (value?.toLowerCase().startsWith("ja")) return "ja";
  if (value?.toLowerCase().startsWith("ko")) return "ko";
  if (value?.toLowerCase().startsWith("es")) return "es";
  return "en";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => {
    if (typeof window === "undefined") return "en";
    return normalizeLocale(localStorage.getItem(LOCALE_STORAGE_KEY));
  });

  const currentOption = languageOptions.find((item) => item.code === locale) || languageOptions[0];
  const language = currentOption.contentLanguage;

  const setLanguage = (lang: Locale) => {
    setLocale(normalizeLocale(lang));
  };

  useEffect(() => {
    localStorage.setItem(LOCALE_STORAGE_KEY, locale);
    localStorage.setItem("ynx-lang", language);
    document.documentElement.lang = locale;
    document.documentElement.dataset.locale = locale;
  }, [language, locale]);

  const t = useMemo(() => {
    return (key: string) => {
      const localePack = translations[locale] || translations.en;
      return localePack[key as TranslationKey] || translations.en[key as TranslationKey] || key;
    };
  }, [locale]);

  return (
    <LanguageContext.Provider value={{ language, locale, languages: languageOptions, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useTranslation must be used within a LanguageProvider");
  }
  return context;
}
